dvc_event_radar/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('myapp.urls')),      # routes all other requests to myapp
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

myapp/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views
from django.urls import reverse_lazy
from .views import CustomPasswordChangeView

urlpatterns = [
    path("", views.home, name='home'),
    # path("calendar/", views.calendar, name='calendar'),
    path('calendar/', views.calendar_view, name='calendar'),  # use calendar_view
    path("event_map/", views.event_map, name="map"),
    path("login/", views.app_login, name="login"),
    path("logout/", views.app_logout, name="logout"),
    path("register/", views.register, name="register"),
    path("event_detail/<int:event_id>/", views.event_detail, name="event_detail"),
    path('favorite/<int:event_id>/', views.mark_favorite, name='mark_favorite'),
    path("add_event/", views.add_event, name="add_event"),
    path("manage-events/", views.manage_events, name="manage_events"),
    path("manage-events/edit/<int:event_id>/", views.edit_event, name="edit_event"),
    path("manage-events/delete/<int:event_id>/", views.delete_event, name="delete_event"),
    path("manage-users/", views.manage_users, name="manage_users"),
    path("manage-users/change-role/<int:user_id>/", views.change_user_role, name="change_user_role"),
    path("manage-users/delete/<int:user_id>/", views.delete_user, name="delete_user"),
    path("profile/", views.user_profile, name="user_profile"),

    path('password_change/', CustomPasswordChangeView.as_view(), name='password_change')
]

myapp/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models import Q 
from django.utils import timezone
from datetime import datetime
from django.conf import settings
import os
import re

def user_avatar_path(instance, filename):
    ext = filename.split('.')[-1]
    # instance.user.id will always exist here because user is saved
    return os.path.join('avatars', str(instance.user.id), f'avatar.{ext}')

class Users(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    DVC_ID = models.CharField(max_length=10,default=None, blank=True, null=True)
    role = models.CharField(max_length=30)
    avatar_url = models.ImageField(
        upload_to=user_avatar_path,  # new path function
        blank=True,
        null=True
    )
    biography = models.TextField(blank=True, null=True)  # <-- add this
    links = models.TextField(blank=True, null=True)      # <-- add this
    
    def __str__(self):
        return self.user.username
    
    class Meta:
        verbose_name = "User"
        verbose_name_plural = "Users"
        
def event_image_path(instance, filename):
    # instance.id won't exist until saved for the first time, so we handle that
    ext = filename.split('.')[-1]
    if instance.id:
        filename = f'{instance.id}.{ext}'
    else:
        filename = f'temp.{ext}'  # temporary name, will rename after save
    return os.path.join('events', str(instance.id or 'temp'), filename)

class EventSearch(models.Manager):
    # If you surround your query with " " , it searches events containing the exact phrase 
    # If you search without quotemarks, it earches posts that contains all the words in the query
    # Ex) If you search `Coffee break` events like `break with coffee` appear 
    # Not Case sensitive
    def search(self, query):
        phrases = re.findall(r'"(.*?)"', query)
        remaining = re.sub(r'"(.*?)"', '', query)
        words = [w for w in remaining.split() if w] 
        
        q_objects = Q()
        
        # Exact phrase search
        for phrase in phrases:
            q_objects |= Q(name__icontains=phrase) | Q(description__icontains=phrase)  | Q(location__icontains=phrase)
        # Default search
        for word in words:
            q_objects &= Q(name__icontains=word) | Q(description__icontains=word) | Q(location__icontains=word)
            
        return self.get_queryset().filter(q_objects).distinct()

class Events(models.Model): 
    EVENT_TYPES = [('Sports', 'Sports'), ('Clubs', 'Clubs'),('Career & Academic', 'Career & Academic'), ('Free Food', 'Free Food'), ('General', 'General')]    
    CAMPUS_CHOICES = [('Pleasant Hill', 'Pleasant Hill'),('San Ramon', 'San Ramon'),('Virtual', 'Virtual')]
    PH_BUILDINGS = [
        ('A', 'Art Complex'), ('AB', 'Administration'), ('BC', 'Book Center'), ('BWL', 'Business & World Language'), 
        ('ECN', 'Early Childhood Education North'), ('ECS', 'Early Childhood Education South'), ('ET', 'Engineering Technology'),
        ('ETT', 'Engineering Technology Temporary'), ('FO', 'Faculty Offices'), ('H', 'Humanities'), ('HFO', 'Health Faculty Offices'),
        ('HRT', 'Horticulture'), ('HSF', 'Hospitality Studies & Food Court'), ('KIN', 'Kinesiology'), ('L', 'Library'), ('LA', 'Liberal Arts'),
        ('LC', 'Learning Center'), ('LCA', 'Learning Communities Annex'), ('LS', 'Life Sciences'), ('M', 'Music'), ('MA', 'Mathematics'),
        ('PAO', 'Performing Arts Office'), ('PL', 'Planetarium'), ('POL', 'Police Services'), ('PS', 'Physical Science'),
        ('SSC', 'Student Services Center'), ('ST', 'Science and Technology Center'), ('SU', 'Student Union'), ('W', 'Warehouse'),
        ('WLC', 'West Library Classrooms'), ('AQ', 'Aquatics'), ('FBO', 'Football Office'), ('FH', 'Field House'), ('FTX', 'Fitness & Exercise'),
        ('GYM', 'Gym'), ('PB', 'Press Box'), ('AR', 'Arena Theater'), ('PAC', 'Performing Arts Center'), ('CCC', 'Community Conference Center'),
        ('CP', 'Commons Plaza'), ('DR', 'Diablo Room'), ('F', 'Forums'), ('LQ', 'Library Quad')
    ]
    SR_BUILDINGS = [
        ('SR-WEST', 'West Building'), ('SR-EAST', 'East Building'), ('SR-LC', 'Learning Commons'), ('SR-LIB', 'Library'), ('SR-MP', 'Mechanical Plant'),
    ]
    BUILDING_CODES = (
        PH_BUILDINGS +
        SR_BUILDINGS +
        [('VR', 'Virtual')]
    )
    BUILDING_COORDINATES = {
        # Pleasant Hill
        "A":   (37.96970240752903, -122.06857796884242),    # Art Complex
        "AB":  (37.96857499999999, -122.07312000000002),    # Administration Building
        "BC":  (37.96856863253504, -122.07127399999990),    # Book Center
        "BWL": (37.96950801850639, -122.07254094329996),    # Business & World Language
        "ECN": (37.96950142338789, -122.07299000000006),    # Early Childhood Education North
        "ECS": (37.96924697952306, -122.07296887432731),    # Early Childhood Education South
        "ET":  (37.96713388859415, -122.07123174105897),    # Engineering Technology
        "ETT": (37.96974361261291, -122.07113046399996),    # Engineering Technology Temporary
        "FO":  (37.96879881982005, -122.07261652700004),    # Faculty Offices
        "H":   (37.96948677554036, -122.07200269484486),    # Humanities
        "HFO": (37.96833986589479, -122.06922201553477),    # Health Faculty Offices
        "HRT": (37.96958995495550, -122.06798926353783),    # Horticulture
        "HSF": (37.96928864063594, -122.07121569045374),    # Hospitality Studies & Food Court
        "KIN": (37.96896264231282, -122.06812093067082),    # Kinesiology
        "L":   (37.96762096728274, -122.07242808476262),    # Library
        "LA":  (37.96880663435614, -122.07200613616711),    # Liberal Arts
        "LC":  (37.96827350000034, -122.07256299999995),    # Learning Center
        "LCA": (37.96830550000005, -122.07213943000002),    # Learning Communities Annex
        "LS":  (37.96738624666404, -122.07384145200661),    # Life Sciences
        "M":   (37.96801628299996, -122.06980966686377),    # Music
        "MA":  (37.96810862319616, -122.07115637248642),    # Mathematics
        "PAO": (37.96967800000055, -122.06986905000002),    # Performing Arts Office
        "PL":  (37.96782047153108, -122.07343608834377),    # Planetarium
        "POL": (37.96741900000001, -122.07056399999999),    # Police Services
        "PS":  (37.96744647155537, -122.07314736936552),    # Physical Science
        "SSC": (37.96891523533683, -122.07135448895589),    # Student Services Center
        "ST":  (37.96828411387047, -122.07387406503243),    # Science and Technology Center
        "SU":  (37.96896853239968, -122.07012823035115),    # Student Union
        "W":   (37.97001309046124, -122.06760005702555),    # Warehouse
        "WLC": (37.96753708154396, -122.07283561241345),    # West Library Classrooms
        "AQ":  (37.96871113961416, -122.06849828158062),    # Aquatics
        "FBO": (37.96752575809212, -122.06838736122332),    # Football Office
        "FH":  (37.96799047153086, -122.06886883834257),    # Field House
        "FTX": (37.96931903111456, -122.06887875271894),    # Fitness & Exercise
        "GYM": (37.96829172994966, -122.06875502606068),    # Gym
        "PB":  (37.96701950000009, -122.06959786249988),    # Press Box
        "AR":  (37.96922400000022, -122.06971000000016),    # Arena Theater
        "PAC": (37.96944105691815, -122.06996933834286),    # Performing Arts Center
        "CCC": (37.96973561953551, -122.07227012028410),    # Community Conference Center
        "CP":  (37.96904845587510, -122.07072091984182),    # Commons Plaza
        "LQ":  (37.96798978512093, -122.07230950939937),    # Library Quad

        # San Ramon
        "SR-WEST": (37.75496847390289, -121.91041226441861),      # San Ramon West Building
        "SR-EAST": (37.75473372697604, -121.90974463229286),      # San Ramon East Building
        "SR-LC":   (37.75485993400142, -121.91081279723862),      # San Ramon Learning Commons
        "SR-LIB":  (37.75466158409603, -121.91027992055231),      # San Ramon Library
        "SR-MP":   (37.75498194513493, -121.91125603403335),      # San Ramon Mechanical Plant

        # Virtual
        "VR": None,
    }
    
    author_ID = models.ForeignKey(Users, on_delete=models.CASCADE)
    name = models.CharField(max_length=100)
    description = models.CharField(max_length=10000)
    date = models.DateField(default=timezone.now)
    start_time = models.CharField(max_length=100)
    end_time = models.CharField(max_length=100)
    location = models.CharField(max_length=100, blank=True, null=True)
    campus = models.CharField(max_length=100, choices=CAMPUS_CHOICES)
    building_code = models.CharField(
        max_length=10,
        choices=BUILDING_CODES,
        default = "VR",
        blank=True,
        null=True,
        help_text="Select a building for on-campus events (VR for Virtual)."
    )
    event_type = models.CharField(max_length=100, choices=EVENT_TYPES)
    image = models.ImageField(
        upload_to=event_image_path,  # folder inside MEDIA_ROOT
        default="default.jpg",  # optional default image
        blank=True,
        null=True
    )
    
    objects = EventSearch()
    
    @property 
    def start_time_obj(self):
        try:
            return datetime.strptime(self.start_time.strip(), "%I:%M %p").time()
        except Exception:
            return None
    
    @property
    def end_time_obj(self):
        try:    
            return datetime.strptime(self.end_time.strip(), "%I:%M %p").time()
        except Exception:
            return None
            
    @property
    def image_or_default(self):
        try: 
            if self.image and os.path.isfile(self.image.path):
                return self.image.url
        except ValueError:

myapp/templates/base_profile.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>{% block title %} Django App {% endblock %}</title>
    <link rel="stylesheet" href="{% static 'home.css' %}" type="text/css">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" />
    <style>
        body {
            font-family: 'Helvetica Neue', Arial, Helvetica, sans-serif;
            background-color: #f8f9fa; 
        }

        .card, .btn, .form-control {
            font-family: inherit;
        }
    </style>
</head>

<body>
    <div id="topNotification" style="
            position: fixed;
            top: -80px;
            left: 50%;
            transform: translateX(-50%);
            background: #333;
            color: white;
            padding: 15px 25px;
            border-radius: 8px;
            z-index: 9999;
            transition: top 0.4s ease-in-out;
            box-shadow: 0 4px 12px rgba(0,0,0,0.3);
        ">
    </div>

    {% block show_header %}
    <header class="d-flex align-items-center p-3 bg-light border-bottom" style="position: relative;">
        <h1 class="mb-0">
            <a href="{% url 'home' %}" style="text-decoration: none; color: inherit;">
                DVC Events
            </a>
        </h1>
        <div class="button-container" style="position: absolute; right: 20px; top: 50%; transform: translateY(-50%);
           display: flex; flex-direction: column; gap: 5px; align-items: center;">
            {% if user.is_authenticated %}
            <!-- Avatar button -->
            <a href="{% url 'user_profile' %}">
                {% if request.user.users.avatar_url %}
                <img src="{{ request.user.users.avatar_url.url }}" alt="Avatar"
                    style="width:40px; height:40px; border-radius:50%; object-fit:cover; border:2px solid #007bff;">
                {% else %}
                <div style="
                    width: 40px;
                    height: 40px;
                    border-radius: 50%;
                    background: white;
                    color: #007bff;
                    border: 2px solid #007bff;
                    display: flex;
                    align-items: center;
                    justify-content: center;
                    font-weight: bold;
                    font-size: 18px;
                    cursor: pointer;
                ">
                    {{ request.user.first_name|first|upper }}{{ request.user.last_name|first|upper }}
                </div>
                {% endif %}
            </a>

            <!-- Logout button -->
            <a href="{% url 'logout' %}" class="btn btn-danger mt-2 w-100">Logout</a>
            {% else %}
            <a href="{% url 'login' %}" class="btn btn-primary mb-2 w-100">Login</a>
            <a href="{% url 'register' %}" class="btn btn-success w-100">Register</a>
            {% endif %}
        </div>
    </header>
    {% endblock %}

    <div class="container-fluid mt-4">
        {% block content %}{% endblock %}
    </div>

    <!-- GLOBAL SCRIPTS -->
    <script>
        document.querySelectorAll('.toggle-btn').forEach(button => {
            button.addEventListener('click', () => {
                const expanded = button.getAttribute('aria-expanded') === 'true';
                setTimeout(() => {
                    button.textContent = expanded ? '+' : '−';
                }, 150);
            });
        });
    </script>

    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.bundle.min.js"></script>

    <script>
        function showTopMessage(text, type = "info") {
            const box = document.getElementById("topNotification");

            const colors = {
                success: "#28a745",
                error: "#dc3545",
                warning: "#ffc107",
                info: "#17a2b8"
            };

            box.style.background = colors[type] || colors.info;
            box.innerText = text;

            // Slide down
            box.style.top = "20px";

            // Auto-hide
            setTimeout(() => {
                box.style.top = "-80px";
            }, 2500);
        }
    </script>

    <!-- 🔥 IMPORTANT: child templates insert their JS here -->
    {% block scripts %}{% endblock %}
</body>

</html>

myapp/templates/edit_events.html
{% extends "base.html" %}
{% block title %}Edit Event{% endblock %}

{% block content %}
<div class="container mt-5">
    <h2>Edit Event: {{ event.name }}</h2>
    <p>Form goes here...</p>
</div>
{% endblock %}

myapp/templates/event_form.html
{% extends 'base.html' %}
{% block title %}{{ page_title }}{% endblock %}

{% block page_title %}
{% with url_name=page_title|yesno:"home,manage_events" %}
    <div class="page-header-title-wrapper">
        <button type="button"
                class="map-back-btn"
                onclick="window.location.href='{% url url_name %}'">
            ← Back
        </button>

        <span class="page-title">{{ page_title }}</span>
    </div>
{% endwith %}
{% endblock %}

{% block header_spacer2 %}
<div style="height: 30px;"></div>
{% endblock %}

{% block content %}
<!-- 🔥 Floating top notification -->
<div id="topNotification"
     style="
        position: fixed;
        top: -80px;
        left: 50%;
        transform: translateX(-50%);
        background: #333;
        color: white;
        padding: 15px 25px;
        border-radius: 8px;
        z-index: 9999;
        transition: top 0.5s ease, opacity 0.5s ease;
        opacity: 0;
        box-shadow: 0 4px 12px rgba(0,0,0,0.3);
     ">
</div>

<div class="d-flex justify-content-center mt-5">
    <div class="w-75">
        <form method="POST" enctype="multipart/form-data">
            {% csrf_token %}

            <div class="form-group">
                <label for="id_name">{{ form.name.label }}</label>
                {{ form.name }}
                {{ form.name.errors }}
            </div>

            <div class="form-group">
                <label for="id_description">{{ form.description.label }}</label>
                <!-- Quill editor container -->
                <div id="description-editor" style="height: 200px; background: white;"></div>
                <!-- Hidden input to submit HTML to Django -->
                <input type="hidden" name="description" id="id_description" value="{{ form.description.value|safe }}">
                {{ form.description.errors }}
            </div>

            <div class="form-group">
                <label for="id_name">{{ form.date.label }}</label>
                {{ form.date }}
                {{ form.date.errors }}
            </div>

            <!-- Start Time -->
            <div class="form-group">
                <label for="id_name">Start Time</label>
                <div class="d-flex time-group">
                    {{ form.start_hour }}
                    {{ form.start_minute }}
                    {{ form.start_period }}
                </div>

                {% if form.start_hour.errors %}<div class="text-danger">{{ form.start_hour.errors }}</div>{% endif %}
                {% if form.start_minute.errors %}<div class="text-danger">{{ form.start_minute.errors }}</div>{% endif %}
                {% if form.start_period.errors %}<div class="text-danger">{{ form.start_period.errors }}</div>{% endif %}
            </div>

            <!-- End Time -->
            <div class="form-group">
                <label for="id_name">End Time</label>
                <div class="d-flex time-group">
                    {{ form.end_hour }}
                    {{ form.end_minute }}
                    {{ form.end_period }}
                </div>

                {% if form.end_hour.errors %}<div class="text-danger">{{ form.end_hour.errors }}</div>{% endif %}
                {% if form.end_minute.errors %}<div class="text-danger">{{ form.end_minute.errors }}</div>{% endif %}
                {% if form.end_period.errors %}<div class="text-danger">{{ form.end_period.errors }}</div>{% endif %}
            </div>

            <div class="form-group">
                <label for="id_location">Location / Building</label>
                {{ form.location }}
                {{ form.location.errors }}
            </div>

            <div class="form-group">
                <label for="id_location">Location / Building Code</label>
                {{ form.building_code }}
                {{ form.building_code.errors }}
            </div>

            <div class="form-group">
                <label for="id_name">{{ form.campus.label }}</label>
                {{ form.campus }}
                {{ form.campus.errors }}
            </div>

            <div class="form-group">
                <label for="id_name">{{ form.event_type.label }}</label>
                {{ form.event_type }}
                {{ form.event_type.errors }}
            </div>

            <div class="form-group">
                <label for="id_image">{{ form.image.label }}</label>
                <div class="file-input-wrapper">
                    <label class="custom-file-btn">
                        {{ form.image }}
                    </label>
                </div>
                {{ form.image.errors }}
            </div>

            <button type="submit" class="btn btn-primary w-100">
                {% if page_title == "Add Event" %}
                    Create Event
                {% else %}
                    Save Changes
                {% endif %}
            </button>
        </form>

        <!-- Bottom Cancel/Home Button -->
        <div class="text-center mt-3 mb-5">
            <a href="{% url 'home' %}" class="btn btn-secondary w-100">Cancel</a>
        </div>
    </div>
</div>

<style>
/* Title */
.page-header-title-wrapper {
    position: relative;
    width: 100%;
    height: 80px;
}

.page-title {
    position: absolute;
    left: 50%;
    transform: translateX(calc(-50% - 22%));
    font-weight: bold;
    font-size: 63px;
    color: #017550;
    white-space: nowrap;
}

/* Back button */
.map-back-btn {
    position: absolute;
    top: 16%;
    left: 0;
    margin-left: 10%;
    padding: 12px 20px;
    background: white;          /* white by default */
    color: #0a7a33;             /* green border/text */
    border: 2px solid #0a7a33; 
    border-radius: 8px;
    font-weight: 600;
    font-size: 1rem;
    cursor: pointer;
    transition: all 0.3s ease;
    outline: none !important;
    box-shadow: none !important;
}

.map-back-btn:hover {
    background-color: #0a7a33; /* fill green on hover */
    color: white;               /* text turns white */
    transform: translateY(-1px);
}

/* Form group wrapper */
.form-group {
    margin-bottom: 24px;
}

/* Labels */
.form-group label {
    display: block;
    font-size: 1.1rem;      /* slightly bigger */
    font-weight: 700;       /* bold */
    color: #173f6c;         /* stronger green color */
    margin-bottom: 8px;
    font-style: normal;     /* remove italic for clarity */
    font-size: 20px;
}

/* Inputs & textareas */
.form-group input,
.form-group select,
.form-group textarea {
    width: 100%;
    padding: 16px 20px;
    border: 2px solid #e0e0e0;
    border-radius: 50px;
    font-size: 1em;
    outline: none;
    transition: all 0.3s ease;
    background: white;
}

.form-group textarea {
    border-radius: 20px;
    min-height: 100px;
    resize: vertical;
}

/* Focus effect */
.form-group input:focus,
.form-group select:focus,
.form-group textarea:focus {
    border-color: #5e35b1;
    box-shadow: 0 0 0 3px rgba(94, 53, 177, 0.1);
}

.form-group input,
.form-group select {
    height: 60px; /* or whatever height you prefer */
    padding: 0 20px; /* vertical padding handled by height */
    border-radius: 50px; /* keep round border for normal inputs */
    box-sizing: border-box;
}

.time-group select,
.time-group input {
    border-radius: 0; /* remove rounded corners for middle elements */
    height: 60px;
    padding: 0 15px;
    border: 2px solid #e0e0e0;
    outline: none;
    transition: all 0.3s ease;
}

/* Left-most element: round the left edge (input or select) */
.time-group > :first-child {
    border-top-left-radius: 50px;
    border-bottom-left-radius: 50px;
}

/* Right-most element: round the right edge (input or select) */
.time-group > :last-child {
    border-top-right-radius: 50px;
    border-bottom-right-radius: 50px;
}

/* Focus effect */
.time-group input:focus,
.time-group select:focus {
    border-color: #5e35b1;
    box-shadow: 0 0 0 3px rgba(94, 53, 177, 0.1);
}

/* Image input wrapper */
.file-input-wrapper {
    display: flex;
    align-items: center;       /* vertically center children */
    gap: 12px;
    height: 60px;              /* same as other inputs */
    border-radius: 50px;       /* round edges for the box */
    border: 2px solid #e0e0e0; /* border like other inputs */
    padding: 0 20px;
    background: white;
    box-sizing: border-box;
}

/* The file input itself takes no extra border, just fills height */
.file-input-wrapper input[type="file"] {
    flex: 1;
    height: 100%;
    background: transparent;
    border: none;
    cursor: pointer;
    font-size: 1.2rem;
}

/* Only the button inside the file input */
.file-input-wrapper input[type="file"]::-webkit-file-upload-button {
    margin-top: 7px !important;
    border: none;
    border-radius: 20px;       /* soft rounded button */
    background-color: #5D2E8F; /* purple */
    color: white;
    font-weight: bold;
    padding: 8px 15px;
    margin: auto 0;            /* vertically center inside wrapper */
    cursor: pointer;
    font-size: 1rem;
    transition: background 0.3s ease;
}

.file-input-wrapper input[type="file"]::-webkit-file-upload-button:hover {
    background-color: #5D2E8F;
    font-size: 1.2rem;
}

/* Firefox */
.file-input-wrapper input[type="file"]::-moz-file-upload-button {
    border: none;
    border-radius: 20px;
    background-color: #5D2E8F;
    color: white;
    padding: 8px 15px;
    cursor: pointer;
    font-size: 1rem;
    transition: background 0.3s ease;
}

.file-input-wrapper input[type="file"]::-moz-file-upload-button:hover {
    background-color: #5D2E8F;
}

/* Primary submit button */
.btn-primary {
    margin-top: 40px;
    background-color: #017550;
    color: white;
    border: 2px solid #017550;
    border-radius: 50px;
    padding: 16px 0;
    font-size: 1.1rem;
    font-weight: 600;
    transition: all 0.3s ease;
}

.btn-primary:hover {
    background-color: #005a3d;
    border-color: #005a3d;
    transform: translateY(-2px);
}

/* Secondary cancel button */
.btn-secondary {
    background-color: white;
    color: #173f6c;
    border: 2px solid #173f6c;
    border-radius: 50px;
    padding: 16px 0;
    font-size: 1.1rem;
    font-weight: 600;
    transition: all 0.3s ease;
}

.btn-secondary:hover {
    background-color: #173f6c;
    color: white;
    transform: translateY(-2px);
}

#description-editor {
    border: 2px solid #e0e0e0;
    border-radius: 0 0 20px 20px;
    font-size: 1rem;
    line-height: 1.5;
}

.ql-toolbar.ql-snow {
    border-radius: 20px 20px 0 0;
    border: 2px solid #e0e0e0;
    border-bottom: none;
}

.ql-container.ql-snow {
    border-radius: 0 0 20px 20px;
    border: 2px solid #e0e0e0;
    border-top: none;
}
</style>

<link href="https://cdn.quilljs.com/1.3.7/quill.snow.css" rel="stylesheet">
<script src="https://cdn.quilljs.com/1.3.7/quill.js"></script>
{% endblock %}

{% block scripts %}
<script>
// Global function
function showTopMessage(text, type = "info") {
    const box = document.getElementById("topNotification");

    const colors = {
        success: "#28a745",
        error: "#dc3545",
        warning: "#ffc107",
        info: "#17a2b8"
    };
    box.textContent = text;
    box.style.background = colors[type] || colors.info;

    // Reset instantly
    box.style.transition = "none";
    box.style.top = "-80px";
    box.style.opacity = "0";
    void box.offsetWidth; // force reflow

    // Apply transition
    box.style.transition = "top 0.5s ease, opacity 0.5s ease";

    // Tiny delay ensures smooth slide
    setTimeout(() => {
        box.style.top = "20px";
        box.style.opacity = "1";
    }, 50);

    // Auto-hide
    setTimeout(() => {
        box.style.top = "-80px";
        box.style.opacity = "0";
    }, 2600);
}
</script>

<script>
var quill = new Quill('#description-editor', {
    theme: 'snow',
    placeholder: 'Enter event description...',
    modules: {
        toolbar: [
            ['bold', 'italic', 'underline'],
            ['link', 'code-block', { 'list': 'bullet' }]
        ]
    }
});

// Load existing content into Quill on edit
const existingHTML = document.getElementById('id_description').value;
if (existingHTML.trim() !== "") {
    quill.root.innerHTML = existingHTML;
}

// Sync to Django input on submit
var form = document.querySelector('form');
form.onsubmit = function() {
    document.querySelector('#id_description').value = quill.root.innerHTML;
};
</script>

{% for message in messages %}
<script>
showTopMessage("{{ message|escapejs }}", "{{ message.tags }}");
</script>
{% endfor %}
{% endblock %}